export const __pagesText = {
  msrp: 'MSRP',
  productListing: {
    Banner: {
      yourLogo: 'Your Logo',
      loginforExclusivePrice:
        ' LOGIN OR CREATE AN ACCOUNT TO SEE EXCLUSIVE PRICING',
      freeShipping: 'FREE SHIPPING ON',
      orderOver: 'ORDERS OVER $4K',
      firstLogoFree: '1ST LOGO FREE',
      uptoTenThousandStiches: 'UP TO 10,000 STITCHES',
      freeProof: 'FREE PROOF',
      onAllOrders: 'ON ALL ORDERS',
      shippingIcon: 'local_shipping',
    },
    loadMoreButton: 'LOAD MORE',
    clearAllButton: 'Clear All',
  },
  home: {},
  ContactUs: {
    contactUsDescription:
      'Our approach as an extension of your brand is to help maintain and build your brand equity with the right partners in the corporate marketplace.',
    contactUs: 'Contact Us',
    chat: 'Chat',
    call: 'Call',
  },
  review: {
    heading: 'Review',
    noReviewAvailable: 'NO REVIEWS ARE AVAILABLE FOR THIS PRODUCT.',
    wantToHearFromYou: 'WE WANT TO HEAR FROM YOU',
    tellUsWhatyouThink:
      'Tell us what you think about this item. It helps us get better atwhat we do, and ultimately provide you with better products',
    writeAReview: 'Write A Review',
    foundHelpfull: 'people found this helpful',
    wasThisHelpfull: 'Was This Helpful? ',
    hateIt: 'I HATE IT',
    loveIt: 'I LOVE IT',
    ok: "IT'S OK",
    DontLike: "I DON'T LIKE IT",
    likeIt: 'I LIKE IT',
    someThingWrong: 'Something went wrong. Try again, Later!!!',
    titleError: 'Error',
    writeReview: 'Write Review',
    postPublicly: 'POST PUBLICLY AS:',
    clear: 'CLEAR',
    reviewSorting: {
      mostRecent: 'Most Recent',
      positiveFirst: 'Positive First',
      negativeFirst: 'Negative First',
      negative: 'negative',
      positive: 'positive',
      latest: 'latest',
    },
    form: {
      description: 'Description For your review',
      headline: 'Headline For your review',
      fileupload: 'Select files to upload',
      dragAndDrop: 'Drag your files here or click in this area.',
      multiple: 'or click to select files',
      submit: 'Submit',
    },
  },
  productInfo: {
    someThingWentWrong: 'Something Went Wrong!!!',
    pleaseUploadLogoLater: 'Please Upload Logo or Add Logo Later for',
    logo: 'Logo',
    minimumOrderForThisColor: 'The minimum order for this color is',
    pleaseIncreaseYourQuantityAndTryAgain:
      'pieces. Please increase your quantity and try again.',
    tenPlus: '10+',
    productRecentlyViewed: {
      recentlyReviews: 'Recent reviews',
      outOf5Starts: 'out of 5 stars',
    },
    somLogoOption: {
      addLogoLater: 'Add Logo Later',
      logoToBeSubmitted: 'Logo to be submitted after order is placed',
      remove: 'Remove',
      selectYourLogo: 'Select your logo :',
      upload: 'Upload',
      selectALocationToPrintLogo: 'Select a location to print your logo :',
      uploadFromLibrary: 'Upload From Library',
    },
    productReviewRating: {
      customerReview: 'Customer Reviews',
      shareYourThought: 'Share your thoughts',
      ifYouHaveUsedThisProductShareThought:
        'If you’ve used this product, share your thoughts with othercustomers',
      overAllRating: 'OVERALL RATING',
      basedOn: 'Based on',
      reviews: 'reviews',
    },
    quantity: 'Quantity:',
    price: 'Price:',
    visibility: 'visibility',
    confirm: 'Confirm',
    checkAvailableInventory: 'Check Available Inventory',
    sizeChart: 'Size Chart',
    additionalDetails: 'Additional details',
    requestAFreeConsulation:
      'Or request a free consultation with one of our experts',
    sku: 'SKU',
    msrp: 'MSRP',
    description: 'Description',
    requestConsultaionProof: 'Request Consultation & Proof',
    availableSizes: 'Available Size(s):',
    companionProduct: 'Companion Product:',
    availableColors: {
      availableColors: 'Available Colors:',
      showless: 'Show Less',
      seeAll: 'See All',
      colors: 'Colors',
    },
    forgotModal: {
      forgotPassword: 'Forget Password',
      back: 'Back',
      notFound: 'not found',
      sentSucess1: 'An email has been sent to ',
      sentSucess2:
        'with a link to reset your password. It may take a few minutes to arrive. If you dont see it in your inbox, please check your spam folder.',
    },
    loginModal: {
      signIn: 'Sign In',
      shopNow: 'SHOP NOW',
      keepMeLoggedIn: 'Keep me logged',
      infoButton: {
        yourPasswordMustHave: 'Your password must have :',
        orMoreCharaters: '8 Or more character',
        atLeastOneNumber: 'At list one number',
        upperAndLowerCaseLetters: 'Upper and lowercase letters',
      },
      forgotPassword: 'Forgot Password?',
      createNewAccount: 'CREATE NEW ACCOUNT',
      emailPlaceHolder: 'Enter the email',
      passwordPlaceHolder: 'Enter the password',
      clickMessage: ` By Clicking "SHOP NOW", you agree to our`,
      termsOfUse: 'Terms of use',
      and: 'and',
      privacyPolicy: 'Privacy policy',
    },
    startOrderModal: {
      color: 'Color :',
      notes: 'Notes :',
      itemTotal: 'Item Total :',
      productInformation: 'Product information',
      customizeLogoOption: {
        customizeYoutOrder: 'Customize Your Order:',
        customizeLogoLater:
          'Customize Logo Later with Dedicated Account Specialist',
        customizeLogoNow: 'Customize Logo Now',
      },
      calculativeFigure: {
        quantitySelected: 'Quantity Selected:',
        pricePerItem: 'Price Per Item:',
        firstLogo: 'First Logo:',
        additionalLogos: 'Additional Logo(s):',
        subTotal: 'Subtotal:',
        additionalSewOutCharges: 'SewOut Charges:',
      },
      askToLogin: {
        loginOrCreateAnAccount: 'LOGIN OR CREATE AN ACCOUNT',
        toSeeDiscountPricing: 'to see discounted pricing on this product.',
        loginCreateAccount: 'Login / Create an account',
      },
      sizePriceQty: {
        size: 'Size',
        price: 'Price',
        qty: 'Qty',
        selectOrInput: {
          thanksForSigningUp: 'Thanks for signing up!',
          outOfStockGetInventoryAlert: 'Out of Stock. Get Inventory Alert.',
          email: 'email',
          notify: 'NOTIFY ME',
          save: 'SAVE',
          clear: 'CLEAR',
          cancel: 'CANCEL ',
        },
      },
    },
    discountPricing: {
      exclusivePricingAvailable: 'EXCLUSIVE PRICING AVAILABLE',
      exclusivePricing: 'EXCLUSIVE PRICING',
      minimumOrder: 'MINIMUM ORDER :',
      price: 'Price:',
      showMsg: `We reserve the right to reject orders that do not meet the {minQty}
      piece minimum per style <br /> and color, exceptions may apply for
      men’s and women’s companion styles per color.`,
      perItem: 'per item',
    },
    availableInventoryModal: {
      availableInventory: 'Available Inventory',
      close: 'Close',
    },
  },
  accountPage: {
    firstName: 'First Name',
    lastName: 'Last Name',
    emailAddress: 'Email Address',
    companyName: 'Company Name',
    currentPassword: 'Current Password',
    youtPasswordMustHave: 'Your password must have :',
    eightMore: '8 Or more character',
    upperOrLowerCase: 'Upper and lowercase letters',
    atLeastOneNumber: 'At least one number',
    passwordUpdate: 'Update Password',
    profileEdit: 'Edit Profile',
    saveBtn: 'Save',
    cancelBtn: 'Cancel',
  },
  Headers: {
    notificationText:
      'Free Logo &amp; Proof on All Orders + Free Shipping on Orders Over $4K',
    order: 'Order',
    accountSetting: 'Account Settings',
    help: 'Help',
    signOut: 'Sign Out',
    login: 'login',
    loginIcon: 'account_circle',
    mycart: 'my cart',
    shoppingCartIcon: 'shopping_cart',
    qty: 'QTY',
    subtotal: 'subtotal',
    totalItemInCartMessage: 'ITEMS IN CART',
    total: 'Total',
    checkoutNow: ' CHECKOUT NOW',
    mobileViewAll: 'View all',
    searchIcon: 'search',
    searchPlaceholder: 'Search',
    rightArrowIcon: 'chevron_right',
    myAccountTittle: 'My Account',
  },
  Wishlist: {
    wishlist: 'WISHLIST',
    removeButton: 'Remove',
    viewButton: 'View',
  },
  PageNotFound: {
    pageNotFound: 'PAGE NOT FOUND',
    backToHome: 'BACK TO HOME PAGE',
  },
  CheckoutPageCardNote1: {
    note: 'Please note that the tax amount on this order is subject to change based on the final invoice, and in accordance with local and state laws',
  },
  CheckoutPageCardNote2: {
    note: 'Your credit card will be authorized at checkout and you will see a pending charge on your bank statement. A sales representative will review the order details once received. Your card will then be charged in 5-7 days after submitted unless confirmed as finalized or otherwise cancelled prior to then.',
  },
  ThankYouPage: {
    Total: 'Product Total:',
    ThankYouLabel: 'Thank You,',
    ForYourOrder: 'FOR YOUR ORDER',
    OrderNumber: 'YOUR ORDER NUMBER IS: ',
    FirstEmailMessage: 'You will receive a confirmation shortly at',
    LastEmailMessage: ', You can access your account at your account ',
    PrintReciept: 'Print Reciept',
    Questions: 'Questions?',
    CallUs: 'Call Us : ',
    Email: 'Email',
    AccordianHeader: 'Detailed Order Reciept :',
    TotalSummary: {
      SubTotal: 'Sub Total:',
      LinePersonalization: 'Line Personalization:',
      LogoCost: 'Additional Logo Costs:',
      Shipping: 'Shipping:',
      Tax: 'Tax:',
      SewOut: 'Sew Out:',
      GrandTotal: 'Grand Total',
      Sku: 'SKU :',
      Color: 'Color :',
      ItemTotal: 'Item Total: ',
      ItemDetails: 'Item Details',
    },
    LogoToBe: 'Logo to be',
    Submitted: 'submitted',
    Logo: 'logo',
    Location: 'Location:',
    LogoPrice: 'Logo Price',
    FirstLogoFree: 'First Logo Free',
    CreatePassword: 'Create Password',
    CreateAccount: 'Create Account',
    Billing : {
      BillTo: 'Bill to:',
      ShipTo: 'Ship to:'
    }
  },
  BreadCrumbs: {
    back: 'Back',
  },
  YouMayAlsoLike: {
    YouMayAlsoLike: 'YOU MAY ALSO LIKE',
  },
  ManageLogo: {
    Waiting: 'Waiting for Approval',
    Approved: 'Approved',
    ApprovedDate: 'Approval Date:',
    Logo: 'Logo',
    ApprovedLogo: 'Approved Logo',
    LogoName: 'Logo Name',
    LogoNumber: 'Logo Number',
    LogoSize: 'Logo Size',
    ProductType: 'Product Type',
    LogoPosition: 'Logo Position',
    Status: 'Status',
    Heading: 'MANAGE LOGO'
  },
  CheckoutPage: {
    cardInstruction:
      'The last three digits \n displayed on the \n back of your card \n or first four \n digits on the front \n of your AMEX.',
  },
  OrderPage: {
    yourOrder: 'Your Order',
    usersOrder: 'Users Order',
    emptyOrder: 'Orders is Empty',
    emptyOrderMessage1: 'There is nothing in your Order',
    emptyOrderMessage2: ' Not to worry: we have lots of other great finds.',
    startShopping: 'START SHOPPING',
    orderNumber: 'ORDER NUMBER',
    userName: ' User Name',
    dateOfOrder: ' DATE OF ORDER',
    totalPrice: '   TOTAL PRICE',
    orderStatus: 'ORDER STATUS',
    viewOrderDetails: 'View Order Details',
    sku: 'SKU ',
    size: 'SIZE',
    color: 'COLOR',
    price: 'PRICE',
    qty: 'QTY',
    unitTotal: 'UNIT TOTAL',
    estimatedPrice: 'ESTIMATED PRICE',
    writeaReview: ' Write A Review',
  },
  CustomizeLater:
    'A Gear Expert will contact you to discuss the customization of this product.',
  CheckLogoApproved: {
    submitFeedback: 'Submit your feedback',
    approveLogo: 'Approve your logo',
    or: 'OR',
    comment: 'Comment:',
    EmbroideryColor: 'Embroidery color:',
    LogoSize: 'Logo size:',
    LogoUploadedOn: 'Logo uploaded on:',
    jpegLogo: 'JPEG LOGO',
    dstLogo: 'DST LOGO',
  },
};
